---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: zigbee2mqtt
      version: 9.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: koenkk/zigbee2mqtt
      tag: latest-dev
    env:
      TZ: "America/Sao_Paulo"
      ZIGBEE2MQTT_DATA: /data
    # https://www.zigbee2mqtt.io/information/configuration.html
    config:
      homeassistant: true
      permit_join: true
      mqtt:
        base_topic: zigbee2mqtt
        server: "mqtt://mosquitto"
      serial:
        port: /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CDD33E2-if00
      # Both of these need to be enabled for the webui
      frontend:
        port: 8080
      experimental:
        new_api: true
      # https://github.com/k8s-at-home/charts/blob/master/charts/stable/zigbee2mqtt/values.yaml#L108
      advanced:
        log_output:
          - console
        log_level: error
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 1Gi
        mountPath: "/data"
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CDD33E2-if00
        hostPathType: CharDevice
    securityContext:
      privileged: true
    affinity: {}
    #   nodeAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       nodeSelectorTerms:
    #       - matchExpressions:
    #         - key: app
    #           operator: In
    #           values:
    #           - zigbee-controller
