---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: 1password-charts
  namespace: flux-system
spec:
  interval: 24h0m0s
  url: https://1password.github.io/connect-helm-charts
  timeout: 3m
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: 1password-repository
  namespace: flux-system
spec:
  interval: 24h0m0s
  url: https://github.com/1Password/connect-helm-charts
  ref:
    branch: main
