---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 100m
  url: https://github.com/stefanprodan/podinfo
  ref:
    branch: master
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmChart
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 100m
  chart: ./charts/podinfo
  sourceRef:
    name: podinfo
    kind: GitRepository
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-helm
  namespace: default
spec:
  interval: 100m
  chart:
    spec:
      chart: podinfo
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      version: 6.0.0
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
