---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: demo
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: app
          image: ghcr.io/yurifrl/demo-state-app:v1.0.0
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /data
          env:
            - name: FILE_PATH
              value: /data/data.log
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: demo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: default
spec:
  ports:
    - protocol: TCP
      name: web
      port: 8080
  selector:
    app: demo
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: demo
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: HostRegexp(`example.{domain}.{ext}`)
      kind: Rule
      services:
        - name: demo
          port: 8080
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
  namespace: default
  labels:
    app: demo
    name: demo-pvc
  annotations:
    backup.velero.io/backup-volumes: demo-pvc
    recurring-job-group.longhorn.io/default: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---

