---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: storage
  labels:
    app: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: data
              mountPath: /usr/share/nginx/html
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: sample-storage-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: storage
  namespace: default
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
  selector:
    app: storage
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: storage
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: HostRegexp(`example.{domain}.{ext}`)
      kind: Rule
      services:
        - name: storage
          port: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-storage-pvc
  namespace: default
  # annotations:
  #   recurring-job-group.longhorn.io/default: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---

