---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      interval: 5m
  values:
    provider: cloudflare
    # extraArgs:
    #   - --domain-filter=monaddaydream.com
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns
            key: cloudflare_api_token
      # - name: CF_API_KEY
      #   valueFrom:
      #     secretKeyRef:
      #       name: external-dns
      #       key: cloudflare_api_key
      # - name: CF_API_EMAIL
      #   value: $EMAIL
