---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://vmware-tanzu.github.io/helm-charts
      chart: velero
      version: 2.26.1
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
      interval: 5m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    image:
      repository: velero/velero
      tag: v1.13.1
    configuration:
      provider: aws
      backupStorageLocation:
        name: default
        bucket: homey-bucket
        config:
          region: sa-east-1
      volumeSnapshotLocation:
        name: aws
        config:
          region: sa-east-1
      resticTimeout: 6h
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.3.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 1500Mi
    # tolerations:
    # - key: "arm"
    #   operator: "Exists"
    # enableHelmHooks: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    snapshotsEnabled: true
    deployRestic: true
    upgradeCRDs: false
    restic:
      podVolumePath: /var/lib/kubelet/pods
      privileged: false
      tolerations:
        - key: "arm"
          operator: "Exists"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
      resources:
        requests:
          memory: 200Mi
          cpu: 15m
        limits:
          memory: 3000Mi
    schedules:
      daily-backup:
        schedule: "0 6 * * *"
        template:
          ttl: "120h"
      test-storage:
        schedule: "2 * * * *"
        template:
          labelSelector:
            matchLabels:
              app: storage-pv
          ttl: "120h"
          includedNamespaces:
            - default
      # mcbr-minecraft-bedrock-hourly:
      #   schedule: "0 */6 * * *"
      #   template:
      #     labelSelector:
      #       matchLabels:
      #         app: mcbr-minecraft-bedrock
      #     ttl: "120h"
      #     includedNamespaces:
      #     - default
      # mcsv-minecraft-hourly:
      #   schedule: "0 * * * *"
      #   template:
      #     labelSelector:
      #       matchLabels:
      #         app: mcsv-minecraft
      #     ttl: "120h"
      #     includedNamespaces:
      #     - default
      # mc-minecraft-hourly:
      #   schedule: "0 */6 * * *"
      #   template:
      #     labelSelector:
      #       matchLabels:
      #         app: mc-minecraft
      #     ttl: "120h"
      #     includedNamespaces:
      #     - default
  valuesFrom:
    - kind: Secret
      name: "velero-credentials"
      optional: false
