---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teleport
  namespace: teleport-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.releases.teleport.dev
      chart: teleport-cluster
      version: 10.2.2
      sourceRef:
        kind: HelmRepository
        name: teleport
        namespace: flux-system
  values:
    clusterName: homey
