apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-vault-0
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  volumeMode: Filesystem
---
apiVersion: v1
kind: Pod
metadata:
  name: data-vault-setup
spec:
  containers:
    - name: file-permissions
      image: busybox:1.36
      command: ["chown", "-R", " ", "/vault/data"]
      securityContext:
        runAsUser: 0
        privileged: true
      volumeMounts:
        - name: data
          mountPath: /vault/data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: data-vault-0
