---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homer
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: homer
      version: 6.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: "America/Sao_Paulo"
    tolerations:
      - key: "arm"
        operator: "Exists"
    ingress:
      main:
        enabled: true
        hosts:
          - host: "homer.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
    configmap:
      # -- Store homer configuration as a ConfigMap
      enabled: true
      # -- Homer configuration. See [image documentation](https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md) for more information.
      # @default -- See values.yaml
      config: |
        title: "Home Server"
        subtitle: "Dashboard"
        # logo: "assets/logo.png"

        # Optional navbar
        links:
          - name: "github"
            icon: "fab fa-github"
            url: "https://github.com/yurifrl/k8s"
            target: "_blank" # optional html tag target attribute

        # Services
        # First level array represents a group.
        # Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
        services:
          - name: "Application"
            icon: "fas fa-code-branch"
            # A path to an image can also be provided. Note that icon take precedence if both icon and logo are set.
            # logo: "path/to/logo"
            items:
              - name: "Home Assistant"
                logo: "assets/tools/sample.png"
                # Alternatively a fa icon can be provided:
                # icon: "fab fa-jenkins"
                subtitle: "Bookmark example"
                tag: "home-automation"
                url: "https://home-assistant.homey.cloud/"
                target: "_blank" # optional html tag target attribute
