---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: 1password
  namespace: vault
spec:
  interval: 5m
  chart:
    spec:
      chart: connect
      version: v1.4.0
      sourceRef:
        kind: HelmRepository
        name: 1password
        namespace: flux-system
      interval: 5m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    operator:
      create: true
