---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: teleport
  namespace: flux-system
spec:
  interval: 24h0m0s
  url: https://charts.releases.teleport.dev
  timeout: 3m
