---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: vernemq
  namespace: flux-system
spec:
  interval: 24h0m0s
  url: https://vernemq.github.io/docker-vernemq
  timeout: 3m
