---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.6.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    persistence:
      defaultClassReplicaCount: 1
      recurringJobSelector:
        enable: true
        jobList: '[
          {
            "name":"snap",
            "task":"snapshot",
            "cron":"*/1 * * * *",
            "retain":5
          },
          {
            "name":"backup",
            "task":"backup",
            "cron":"*/2 * * * *",
            "retain":5
          }
        ]'
    defaultSettings:
      backupTarget: "s3://homey-bucket@sa-east-1/longhorn/"
      backupTargetCredentialSecret: "aws-secret"
      # allowRecurringJobWhileVolumeDetached: ~
      # createDefaultDiskLabeledNodes: ~
      # defaultDataPath: ~
      # defaultDataLocality: ~
      # replicaSoftAntiAffinity: ~
      # replicaAutoBalance: ~
      # storageOverProvisioningPercentage: ~
      # storageMinimalAvailablePercentage: ~
      # upgradeChecker: ~
      # defaultReplicaCount: 1
      # defaultLonghornStaticStorageClass: ~
      # backupstorePollInterval: ~
      # taintToleration: ~
      # systemManagedComponentsNodeSelector: ~
      # priorityClass: ~
      # autoSalvage: ~
      # autoDeletePodWhenVolumeDetachedUnexpectedly: ~
      # disableSchedulingOnCordonedNode: ~
      # replicaZoneSoftAntiAffinity: ~
      # nodeDownPodDeletionPolicy: ~
      # allowNodeDrainWithLastHealthyReplica: ~
      # mkfsExt4Parameters: ~
      # disableReplicaRebuild: ~
      # replicaReplenishmentWaitInterval: ~
      # disableRevisionCounter: ~
      # systemManagedPodsImagePullPolicy: ~
      # allowVolumeCreationWithDegradedAvailability: ~
      # autoCleanupSystemGeneratedSnapshot: ~
      # concurrentAutomaticEngineUpgradePerNodeLimit: ~
      # backingImageCleanupWaitInterval: ~
      # guaranteedEngineManagerCPU: ~
      # guaranteedReplicaManagerCPU: ~
