---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    defaultSettings:
      backupTarget: "s3://yuri-longhorn@sa-east-1/"
      backupTargetCredentialSecret: "aws-secret"
      # allowRecurringJobWhileVolumeDetached: ~
      # createDefaultDiskLabeledNodes: ~
      # defaultDataPath: ~
      # defaultDataLocality: ~
      # replicaSoftAntiAffinity: ~
      # replicaAutoBalance: ~
      # storageOverProvisioningPercentage: ~
      # storageMinimalAvailablePercentage: ~
      # upgradeChecker: ~
      # defaultReplicaCount: ~
      # defaultLonghornStaticStorageClass: ~
      # backupstorePollInterval: ~
      # taintToleration: ~
      # systemManagedComponentsNodeSelector: ~
      # priorityClass: ~
      # autoSalvage: ~
      # autoDeletePodWhenVolumeDetachedUnexpectedly: ~
      # disableSchedulingOnCordonedNode: ~
      # replicaZoneSoftAntiAffinity: ~
      # nodeDownPodDeletionPolicy: ~
      # allowNodeDrainWithLastHealthyReplica: ~
      # mkfsExt4Parameters: ~
      # disableReplicaRebuild: ~
      # replicaReplenishmentWaitInterval: ~
      # disableRevisionCounter: ~
      # systemManagedPodsImagePullPolicy: ~
      # allowVolumeCreationWithDegradedAvailability: ~
      # autoCleanupSystemGeneratedSnapshot: ~
      # concurrentAutomaticEngineUpgradePerNodeLimit: ~
      # backingImageCleanupWaitInterval: ~
      # guaranteedEngineManagerCPU: ~
      # guaranteedReplicaManagerCPU: ~
