---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 24h0m0s
  releaseName: sealed-secrets-controller
  targetNamespace: flux-system
  chart:
    spec:
      # renovate: registryUrl=https://bitnami-labs.github.io/sealed-secrets
      chart: sealed-secrets
      version: 1.15.x
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets-charts
        namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values: {}
